version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6003:6003"
    environment:  # Исправлено
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=appdb
    restart: unless-stopped
    depends_on:  # Исправлено
      - postgres

  postgres:
    image: postgres:13  # Исправлено (добавлен двоеточие)
    environment:  # Исправлено
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    restart: unless-stopped
